#!/bin/bash

cp "../DE/Automatisierte Ablaufsteuerung.drawio"          "../EN/automated hump control.drawio"
cp "../DE/Automatisierte Planung und Planprüfung.drawio"  "../EN/automated planning and plan review.drawio"
cp "../DE/Cloud-Stellwerk.drawio"                         "../EN/cloud interlocking.drawio"
cp "../DE/Dezentrales Stellwerk.drawio"                   "../EN/decentralized interlocking.drawio"
cp "../DE/Emotions- und Absichtserkennung.drawio"         "../EN/emotion and intent recognition.drawio"
cp "../DE/Ferngesteuerte Fahrzeuge.drawio"                "../EN/remote controlled rolling stock.drawio"
cp "../DE/Güterwegemanagement.drawio"                     "../EN/freight route management.drawio"
cp "../DE/Intelligente Instandhaltung.drawio"             "../EN/predictive maintenance.drawio"
cp "../DE/Intermodale Güterabfertigung.drawio"            "../EN/intermodal freight handling.drawio"
cp "../DE/Intermodale Reisekette.drawio"                  "../EN/intermodal travel chain.drawio"
cp "../DE/Kontaktlose Fahrscheinkontrolle.drawio"         "../EN/contactless ticket control.drawio"
cp "../DE/Optimierte Reise- und Preisgestaltung.drawio"   "../EN/optimised travel and price arrangement.drawio"
cp "../DE/Optimierung der Fahrgastwechselzeit.drawio"     "../EN/optimization of passenger changeover time.drawio"
cp "../DE/Personenidentifizierung.drawio"                 "../EN/identification of persons.drawio"
cp "../DE/Reise- und Lebensmanagement.drawio"             "../EN/travel and life management.drawio"
cp "../DE/Reisendenlenkung.drawio"                        "../EN/passenger guidance through the train station.drawio"
cp "../DE/Steuernder Durchgriff der Disposition.drawio"   "../EN/steering action for scheduling.drawio"
cp "../DE/Virtuelles Kuppeln.drawio"                      "../EN/virtual coupling.drawio"
cp "../DE/Vollautomatisiertes Fahren.drawio"              "../EN/fully automated driving.drawio"
cp "../DE/Vorort-Informationen.drawio"                    "../EN/on-site information.drawio"
cp "../DE/Zugsicherung mit ETCS.drawio"                   "../EN/ETCS train protection.drawio"
